<?php

namespace App\Modules\mattarnster;

use App\Modules\Module;
use App\Models\Post;

class ExampleModule implements Module {

  function register() {
    $module_registry = ModuleRegistry::getInstance();
    $module_registry::register('ExampleModule');
  }

  function renderableViewTemplates() {
    return array(
      "HelloWorldMessage" => "<p>This message was generated by the ExampleModule</p>",
      "GeneratedByFunction" => $this->generateMarkup(),
      "PostViewMarkup" => $this->generatePostViewMarkup(),
    );
  }

  function generateMarkup() {
    return "<p>This markup was generated by a function</p>";
  }

  function generatePostViewMarkup() {
    $posts = new Post();
    $posts = $posts->fetchAll();
    //die(var_dump($posts));
    $output = [];
    
    foreach ($posts as $post) {
      $output[] = '<div class="post">$post->post_text</div>';
    }

    return $output;
  }

}